-- General information
Simulation {
    name        = 't1',
    description = 'Generated by GiD2GeMA'
}

-- Auxiliary files
dofile('$SIMULATIONDIR/$SIMULATIONNAME_model.lua')
dofile('$SIMULATIONDIR/$SIMULATIONNAME_solution.lua')

-- Generated by GiD2GeMA v1.0.1 developer
