-------------------------------------------------------------
--  State variables
-------------------------------------------------------------
StateVar{id = 'u', dim = 2, description = 'Displacements in the X and Y directions', unit = 'm', format = '8.4f', groupName = 'mechanic'}

-------------------------------------------------------------
--  Cell properties
-------------------------------------------------------------
PropertySet {
    id          = 'MatProp',
    typeName    = 'GemaPropertySet',
    description = 'Material properties',
    properties  = {
        {id = 'E' , description = 'Elastic modulus'                       , unit = 'kPa'  },
        {id = 'nu', description = 'Poisson ratio'                         , unit = ''     },
        {id = 'Kn', description = 'Normal elastic stiffness'              , unit = 'kPa/m'},
        {id = 'Ks', description = 'Shear elastic stiffness at direction 1', unit = 'kPa/m'},
        {id = 'Kt', description = 'Shear elastic stiffness at direction 2', unit = 'kPa/m'},
        {id = 'MEC_material', description = 'Mechanical material type', constMap = constants.MechanicalFemPhysics.materialModels},
    },
    values = {
        -- Material
        {E = 10, nu = 0.0, MEC_material = 'elastic'},
        -- interface
        {Kn = 100, Ks = 100, Kt = 0.0, MEC_material = 'elasticInterface'},
    }
}

PropertySet {
    id          = 'SecProp',
    typeName    = 'GemaPropertySet',
    description = 'Section properties',
    properties  = {
        {id = 'h',  description = 'Element thickness', unit = 'm'},
    },
    values = {
        { h =     1 },
    }
}

-------------------------------------------------------------
--  Mesh definition
-------------------------------------------------------------
-- Number of nodes             : 16
-- Number of continuum elements: 4
-- Number of interface elements: 4
-- Total number of elements    : 8

local mesh_nodes = {
    {1.000000e-03, 1.000000e-03},
    {1.000000e-03, 5.000000e-04},
    {5.000000e-04, 1.000000e-03},
    {5.000000e-04, 1.000000e-03},
    {1.000000e-03, 5.000000e-04}, -- 5
    {5.000000e-04, 5.000000e-04},
    {5.000000e-04, 5.000000e-04},
    {5.000000e-04, 5.000000e-04},
    {5.000000e-04, 5.000000e-04},
    {0.000000e+00, 1.000000e-03}, -- 10
    {1.000000e-03, 0.000000e+00},
    {0.000000e+00, 5.000000e-04},
    {0.000000e+00, 5.000000e-04},
    {5.000000e-04, 0.000000e+00},
    {5.000000e-04, 0.000000e+00}, -- 15
    {0.000000e+00, 0.000000e+00},
}

local Parts_Auto1_Quadrilateral_elements = {
    { 6, 12, 16, 14},
    { 5,  9, 15, 11},
    { 4, 10, 13,  7},
    { 1,  3,  8,  2},
}

mesh_groups_elements = dofile('$SIMULATIONDIR/t1_intMesh.lua')
local mesh_elements = {
    {cellType = 'quad4', cellGroup = 'Parts_Auto1_Quadrilateral', cellList = Parts_Auto1_Quadrilateral_elements, MatProp = 1, SecProp = 1}, -- Parts Auto1
    {cellType = 'int2dl4', cellGroup = 'cohesice_InterfaceLine', cellList = mesh_groups_elements[1], MatProp = 2, SecProp = 1}, -- cohesice
}

Mesh {
    -- General mesh attributes
    id          = 'mesh',
    typeName    = 'GemaMesh.elem',
    description = 'mesh discretization',
    
    -- Mesh dimensions
    coordinateDim  =   2,
    coordinateUnit = 'm',
    
    -- State vars stored in this mesh (per node)
    stateVars = { 'u',},
    
    -- Mesh node coordinates
    nodeData = mesh_nodes,
    
    -- Element properties
    cellProperties = {'MatProp', 'SecProp'},
    
    -- Element data
    cellData = mesh_elements,
    
    -- IntegrationRules
    elementRules = {
        { quad4 = 2, int2dl4 = 2, },
    },
    
}

-------------------------------------------------------------
--  Boundary conditions
-------------------------------------------------------------
BoundaryCondition {
    id   = 'cload',
    type = 'node concentrated forces',
    mesh = 'mesh',
    properties  = {
        {id = 'f',  description = 'External force applied on the node', unit = 'kN', dim = 2},
    },
    nodeValues = {
        {       1, { 0.000000e+00, 1.000000e+01} }, -- Concentrated loads Auto1
        {      10, { 0.000000e+00, 1.000000e+01} }, -- Concentrated loads Auto1
    }
}

BoundaryCondition {
    id   = 'disp',
    type = 'node displacements',
    mesh = 'mesh',
    properties  = {
        {id = 'ux',  description = 'Fixed node displacement in the X direction', unit = 'm', defVal = -9999},
        {id = 'uy',  description = 'Fixed node displacement in the Y direction', unit = 'm', defVal = -9999},
    },
    nodeValues = {
        {      11,  0.000000e+00, 0.000000e+00 }, -- Fixed displacement Auto1
        {      14,  0.000000e+00, 0.000000e+00 }, -- Fixed displacement Auto1
        {      16,  0.000000e+00, 0.000000e+00 }, -- Fixed displacement Auto1
    }
}

-- Generated by GiD2GeMA v1.0.1 developer
